### PR TITLE
Remove unused build_and_test.md

### PR DESCRIPTION
**Pull request by SteNicholas**
Remove unused contributor guide with `build_and_test.md` and `docs_and_website.md`.

### CODE REVIEW

**Comment by pan3793** [comment]
why `docs_and_website.md` is unused?

**Comment by SteNicholas** [comment]
@pan3793, just follow the community document of Kyuubi. Meanwhile, this contributor guilde is used to website contributor, which is confusing in website whether this guide is contributor guilde of website or project.

**Comment by pan3793** [comment]
How do we guide the contributors to verify the changes of docs then? For example, if something is broken due to bad syntax, how to debug that?

**Comment by SteNicholas** [comment]
@pan3793, I have reverted the removal of `docs_and_website.md`. PTAL.

**Review by pan3793 — APPROVED** [review]

**Pull request merged**
