### PR TITLE
Add Fei Wang as Celeborn commiter

### PR DESCRIPTION
**Pull request by turboFei**

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
Congrats！

**Review by pan3793 — APPROVED** [review]
Congrats!

**Review by cxzl25 — APPROVED** [review]
Congratulations!

**Comment by turboFei** [comment]
thanks all, merging to main

**Comment by cfmcgrady** [comment]
Congrats！

**Comment by mridulm** [comment]
Congratulations !

**Comment by SteNicholas** [comment]
Congratulations!

**Pull request merged**
