### PR TITLE
Add Shaoyun Chen to committers

### PR DESCRIPTION
**Pull request by cxzl25**

### CODE REVIEW

**Review by AngersZhuuuu — APPROVED** [review]
Congratulations!

**Review by cfmcgrady — APPROVED** [review]
Congratulations!

**Comment by waitinfuture** [comment]
Congratulations!

**Review by waitinfuture — APPROVED** [review]
Congrats!

**Comment by SteNicholas** [comment]
Congratulations!

**Comment by cxzl25** [comment]
Thank you all for your help! @AngersZhuuuu @cfmcgrady @waitinfuture @SteNicholas @pan3793

**Comment by waitinfuture** [comment]
> Thank you all for your help! @AngersZhuuuu @cfmcgrady @waitinfuture @SteNicholas @pan3793

Thank you for your contribution : )

**Pull request merged**
